/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AFFECTATION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getAFFECTATION()
 * @model
 * @generated
 */
public interface AFFECTATION extends Instruction
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getAFFECTATION_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(SELECTOR)
   * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getAFFECTATION_Selector()
   * @model containment="true"
   * @generated
   */
  SELECTOR getSelector();

  /**
   * Sets the value of the '{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(SELECTOR value);

} // AFFECTATION
