/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserAutomationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browserAutomation";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/imt/browserautomation/BrowserAutomation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browserAutomation";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserAutomationPackage eINSTANCE = org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.TestImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getTest()
   * @generated
   */
  int TEST = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__NAME = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.InstructionImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.AFFECTATIONImpl <em>AFFECTATION</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.AFFECTATIONImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getAFFECTATION()
   * @generated
   */
  int AFFECTATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__SELECTOR = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>AFFECTATION</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.SELECTORImpl <em>SELECTOR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.SELECTORImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getSELECTOR()
   * @generated
   */
  int SELECTOR = 3;

  /**
   * The number of structural features of the '<em>SELECTOR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.VerifiableImpl <em>Verifiable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.VerifiableImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getVerifiable()
   * @generated
   */
  int VERIFIABLE = 16;

  /**
   * The number of structural features of the '<em>Verifiable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFIABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.RefElementImpl <em>Ref Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.RefElementImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getRefElement()
   * @generated
   */
  int REF_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_ELEMENT__REF = VERIFIABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_ELEMENT_FEATURE_COUNT = VERIFIABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.ElementImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__ID = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.OPEN_BROWSERImpl <em>OPEN BROWSER</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.OPEN_BROWSERImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getOPEN_BROWSER()
   * @generated
   */
  int OPEN_BROWSER = 6;

  /**
   * The number of structural features of the '<em>OPEN BROWSER</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_BROWSER_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.GO_TO_URLImpl <em>GO TO URL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.GO_TO_URLImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getGO_TO_URL()
   * @generated
   */
  int GO_TO_URL = 7;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_URL__URL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>GO TO URL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_URL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CLICK_ONImpl <em>CLICK ON</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.CLICK_ONImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCLICK_ON()
   * @generated
   */
  int CLICK_ON = 8;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__ELEMENT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>CLICK ON</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.VERIFY_THATImpl <em>VERIFY THAT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.VERIFY_THATImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getVERIFY_THAT()
   * @generated
   */
  int VERIFY_THAT = 9;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_THAT__ELEMENT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>VERIFY THAT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_THAT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.INSERT_ONImpl <em>INSERT ON</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.INSERT_ONImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getINSERT_ON()
   * @generated
   */
  int INSERT_ON = 10;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_ON__ELEMENT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_ON__DATA = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>INSERT ON</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_ON_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CHECK_BOXEImpl <em>CHECK BOXE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.CHECK_BOXEImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCHECK_BOXE()
   * @generated
   */
  int CHECK_BOXE = 11;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BOXE__ELEMENT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>CHECK BOXE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BOXE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CHOOSE_COMBOBOXImpl <em>CHOOSE COMBOBOX</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.CHOOSE_COMBOBOXImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCHOOSE_COMBOBOX()
   * @generated
   */
  int CHOOSE_COMBOBOX = 12;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE_COMBOBOX__ELEMENT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE_COMBOBOX__DATA = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>CHOOSE COMBOBOX</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE_COMBOBOX_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.READ_ONImpl <em>READ ON</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.READ_ONImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getREAD_ON()
   * @generated
   */
  int READ_ON = 13;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_ON__ELEMENT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>READ ON</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_ON_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.ReadableImpl <em>Readable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.ReadableImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getReadable()
   * @generated
   */
  int READABLE = 14;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READABLE__PARAMS = SELECTOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READABLE__NUMBER = SELECTOR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Readable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READABLE_FEATURE_COUNT = SELECTOR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.InsertableImpl <em>Insertable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.InsertableImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getInsertable()
   * @generated
   */
  int INSERTABLE = 15;

  /**
   * The number of structural features of the '<em>Insertable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERTABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.ClickableImpl <em>Clickable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.ClickableImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getClickable()
   * @generated
   */
  int CLICKABLE = 17;

  /**
   * The number of structural features of the '<em>Clickable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICKABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.COMBOBOXImpl <em>COMBOBOX</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.COMBOBOXImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCOMBOBOX()
   * @generated
   */
  int COMBOBOX = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__NAME = CLICKABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>COMBOBOX</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX_FEATURE_COUNT = CLICKABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CHECKBOXImpl <em>CHECKBOX</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.CHECKBOXImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCHECKBOX()
   * @generated
   */
  int CHECKBOX = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__NAME = 0;

  /**
   * The number of structural features of the '<em>CHECKBOX</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.SEARCH_FIELDImpl <em>SEARCH FIELD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.SEARCH_FIELDImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getSEARCH_FIELD()
   * @generated
   */
  int SEARCH_FIELD = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEARCH_FIELD__NAME = INSERTABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SEARCH FIELD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEARCH_FIELD_FEATURE_COUNT = INSERTABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.TEXTImpl <em>TEXT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.TEXTImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getTEXT()
   * @generated
   */
  int TEXT = 21;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__PARAMS = READABLE__PARAMS;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NUMBER = READABLE__NUMBER;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NAME = READABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>TEXT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = READABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.BUTTONImpl <em>BUTTON</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BUTTONImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getBUTTON()
   * @generated
   */
  int BUTTON = 22;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__PARAMS = READABLE__PARAMS;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NUMBER = READABLE__NUMBER;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = READABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>BUTTON</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = READABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.LINKImpl <em>LINK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.LINKImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getLINK()
   * @generated
   */
  int LINK = 23;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__PARAMS = READABLE__PARAMS;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NUMBER = READABLE__NUMBER;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__URL = READABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>LINK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = READABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.IMAGEImpl <em>IMAGE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.IMAGEImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getIMAGE()
   * @generated
   */
  int IMAGE = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__NAME = VERIFIABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__PARAMS = VERIFIABLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>IMAGE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = VERIFIABLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.PARAMSImpl <em>PARAMS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.PARAMSImpl
   * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getPARAMS()
   * @generated
   */
  int PARAMS = 25;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS__VALUE = 1;

  /**
   * The number of structural features of the '<em>PARAMS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.Test#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Test#getName()
   * @see #getTest()
   * @generated
   */
  EAttribute getTest_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.imt.browserautomation.browserAutomation.Test#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Test#getInstructions()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Instructions();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION <em>AFFECTATION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AFFECTATION</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.AFFECTATION
   * @generated
   */
  EClass getAFFECTATION();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getName()
   * @see #getAFFECTATION()
   * @generated
   */
  EAttribute getAFFECTATION_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.AFFECTATION#getSelector()
   * @see #getAFFECTATION()
   * @generated
   */
  EReference getAFFECTATION_Selector();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.SELECTOR <em>SELECTOR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SELECTOR</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.SELECTOR
   * @generated
   */
  EClass getSELECTOR();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.RefElement <em>Ref Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.RefElement
   * @generated
   */
  EClass getRefElement();

  /**
   * Returns the meta object for the reference '{@link org.xtext.imt.browserautomation.browserAutomation.RefElement#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.RefElement#getRef()
   * @see #getRefElement()
   * @generated
   */
  EReference getRefElement_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.Element#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Element#getId()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.OPEN_BROWSER <em>OPEN BROWSER</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>OPEN BROWSER</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.OPEN_BROWSER
   * @generated
   */
  EClass getOPEN_BROWSER();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.GO_TO_URL <em>GO TO URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GO TO URL</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.GO_TO_URL
   * @generated
   */
  EClass getGO_TO_URL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.GO_TO_URL#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.GO_TO_URL#getUrl()
   * @see #getGO_TO_URL()
   * @generated
   */
  EAttribute getGO_TO_URL_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.CLICK_ON <em>CLICK ON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CLICK ON</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CLICK_ON
   * @generated
   */
  EClass getCLICK_ON();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.browserautomation.browserAutomation.CLICK_ON#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CLICK_ON#getElement()
   * @see #getCLICK_ON()
   * @generated
   */
  EReference getCLICK_ON_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.VERIFY_THAT <em>VERIFY THAT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>VERIFY THAT</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.VERIFY_THAT
   * @generated
   */
  EClass getVERIFY_THAT();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.browserautomation.browserAutomation.VERIFY_THAT#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.VERIFY_THAT#getElement()
   * @see #getVERIFY_THAT()
   * @generated
   */
  EReference getVERIFY_THAT_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.INSERT_ON <em>INSERT ON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INSERT ON</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.INSERT_ON
   * @generated
   */
  EClass getINSERT_ON();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.browserautomation.browserAutomation.INSERT_ON#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.INSERT_ON#getElement()
   * @see #getINSERT_ON()
   * @generated
   */
  EReference getINSERT_ON_Element();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.INSERT_ON#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.INSERT_ON#getData()
   * @see #getINSERT_ON()
   * @generated
   */
  EAttribute getINSERT_ON_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.CHECK_BOXE <em>CHECK BOXE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CHECK BOXE</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHECK_BOXE
   * @generated
   */
  EClass getCHECK_BOXE();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.imt.browserautomation.browserAutomation.CHECK_BOXE#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHECK_BOXE#getElement()
   * @see #getCHECK_BOXE()
   * @generated
   */
  EReference getCHECK_BOXE_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.CHOOSE_COMBOBOX <em>CHOOSE COMBOBOX</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CHOOSE COMBOBOX</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHOOSE_COMBOBOX
   * @generated
   */
  EClass getCHOOSE_COMBOBOX();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.browserautomation.browserAutomation.CHOOSE_COMBOBOX#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHOOSE_COMBOBOX#getElement()
   * @see #getCHOOSE_COMBOBOX()
   * @generated
   */
  EReference getCHOOSE_COMBOBOX_Element();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.CHOOSE_COMBOBOX#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHOOSE_COMBOBOX#getData()
   * @see #getCHOOSE_COMBOBOX()
   * @generated
   */
  EAttribute getCHOOSE_COMBOBOX_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.READ_ON <em>READ ON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>READ ON</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.READ_ON
   * @generated
   */
  EClass getREAD_ON();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.browserautomation.browserAutomation.READ_ON#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.READ_ON#getElement()
   * @see #getREAD_ON()
   * @generated
   */
  EReference getREAD_ON_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Readable <em>Readable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Readable</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Readable
   * @generated
   */
  EClass getReadable();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.imt.browserautomation.browserAutomation.Readable#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Readable#getParams()
   * @see #getReadable()
   * @generated
   */
  EReference getReadable_Params();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.Readable#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Readable#getNumber()
   * @see #getReadable()
   * @generated
   */
  EAttribute getReadable_Number();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Insertable <em>Insertable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insertable</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Insertable
   * @generated
   */
  EClass getInsertable();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Verifiable <em>Verifiable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verifiable</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Verifiable
   * @generated
   */
  EClass getVerifiable();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.Clickable <em>Clickable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clickable</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.Clickable
   * @generated
   */
  EClass getClickable();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.COMBOBOX <em>COMBOBOX</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COMBOBOX</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.COMBOBOX
   * @generated
   */
  EClass getCOMBOBOX();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.COMBOBOX#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.COMBOBOX#getName()
   * @see #getCOMBOBOX()
   * @generated
   */
  EAttribute getCOMBOBOX_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.CHECKBOX <em>CHECKBOX</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CHECKBOX</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHECKBOX
   * @generated
   */
  EClass getCHECKBOX();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.CHECKBOX#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.CHECKBOX#getName()
   * @see #getCHECKBOX()
   * @generated
   */
  EAttribute getCHECKBOX_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.SEARCH_FIELD <em>SEARCH FIELD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SEARCH FIELD</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.SEARCH_FIELD
   * @generated
   */
  EClass getSEARCH_FIELD();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.SEARCH_FIELD#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.SEARCH_FIELD#getName()
   * @see #getSEARCH_FIELD()
   * @generated
   */
  EAttribute getSEARCH_FIELD_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.TEXT <em>TEXT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TEXT</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.TEXT
   * @generated
   */
  EClass getTEXT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.TEXT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.TEXT#getName()
   * @see #getTEXT()
   * @generated
   */
  EAttribute getTEXT_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.BUTTON <em>BUTTON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BUTTON</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.BUTTON
   * @generated
   */
  EClass getBUTTON();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.BUTTON#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.BUTTON#getName()
   * @see #getBUTTON()
   * @generated
   */
  EAttribute getBUTTON_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.LINK <em>LINK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LINK</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.LINK
   * @generated
   */
  EClass getLINK();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.LINK#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.LINK#getUrl()
   * @see #getLINK()
   * @generated
   */
  EAttribute getLINK_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.IMAGE <em>IMAGE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IMAGE</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.IMAGE
   * @generated
   */
  EClass getIMAGE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.IMAGE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.IMAGE#getName()
   * @see #getIMAGE()
   * @generated
   */
  EAttribute getIMAGE_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.imt.browserautomation.browserAutomation.IMAGE#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.IMAGE#getParams()
   * @see #getIMAGE()
   * @generated
   */
  EReference getIMAGE_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.browserautomation.browserAutomation.PARAMS <em>PARAMS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PARAMS</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.PARAMS
   * @generated
   */
  EClass getPARAMS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.PARAMS#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.PARAMS#getKey()
   * @see #getPARAMS()
   * @generated
   */
  EAttribute getPARAMS_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.browserautomation.browserAutomation.PARAMS#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.imt.browserautomation.browserAutomation.PARAMS#getValue()
   * @see #getPARAMS()
   * @generated
   */
  EAttribute getPARAMS_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserAutomationFactory getBrowserAutomationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.TestImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST__NAME = eINSTANCE.getTest_Name();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__INSTRUCTIONS = eINSTANCE.getTest_Instructions();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.InstructionImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.AFFECTATIONImpl <em>AFFECTATION</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.AFFECTATIONImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getAFFECTATION()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAFFECTATION();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFFECTATION__NAME = eINSTANCE.getAFFECTATION_Name();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__SELECTOR = eINSTANCE.getAFFECTATION_Selector();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.SELECTORImpl <em>SELECTOR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.SELECTORImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getSELECTOR()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSELECTOR();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.RefElementImpl <em>Ref Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.RefElementImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getRefElement()
     * @generated
     */
    EClass REF_ELEMENT = eINSTANCE.getRefElement();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REF_ELEMENT__REF = eINSTANCE.getRefElement_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.ElementImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__ID = eINSTANCE.getElement_Id();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.OPEN_BROWSERImpl <em>OPEN BROWSER</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.OPEN_BROWSERImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getOPEN_BROWSER()
     * @generated
     */
    EClass OPEN_BROWSER = eINSTANCE.getOPEN_BROWSER();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.GO_TO_URLImpl <em>GO TO URL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.GO_TO_URLImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getGO_TO_URL()
     * @generated
     */
    EClass GO_TO_URL = eINSTANCE.getGO_TO_URL();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_TO_URL__URL = eINSTANCE.getGO_TO_URL_Url();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CLICK_ONImpl <em>CLICK ON</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.CLICK_ONImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCLICK_ON()
     * @generated
     */
    EClass CLICK_ON = eINSTANCE.getCLICK_ON();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK_ON__ELEMENT = eINSTANCE.getCLICK_ON_Element();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.VERIFY_THATImpl <em>VERIFY THAT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.VERIFY_THATImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getVERIFY_THAT()
     * @generated
     */
    EClass VERIFY_THAT = eINSTANCE.getVERIFY_THAT();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY_THAT__ELEMENT = eINSTANCE.getVERIFY_THAT_Element();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.INSERT_ONImpl <em>INSERT ON</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.INSERT_ONImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getINSERT_ON()
     * @generated
     */
    EClass INSERT_ON = eINSTANCE.getINSERT_ON();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_ON__ELEMENT = eINSTANCE.getINSERT_ON_Element();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_ON__DATA = eINSTANCE.getINSERT_ON_Data();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CHECK_BOXEImpl <em>CHECK BOXE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.CHECK_BOXEImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCHECK_BOXE()
     * @generated
     */
    EClass CHECK_BOXE = eINSTANCE.getCHECK_BOXE();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK_BOXE__ELEMENT = eINSTANCE.getCHECK_BOXE_Element();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CHOOSE_COMBOBOXImpl <em>CHOOSE COMBOBOX</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.CHOOSE_COMBOBOXImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCHOOSE_COMBOBOX()
     * @generated
     */
    EClass CHOOSE_COMBOBOX = eINSTANCE.getCHOOSE_COMBOBOX();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOOSE_COMBOBOX__ELEMENT = eINSTANCE.getCHOOSE_COMBOBOX_Element();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOOSE_COMBOBOX__DATA = eINSTANCE.getCHOOSE_COMBOBOX_Data();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.READ_ONImpl <em>READ ON</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.READ_ONImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getREAD_ON()
     * @generated
     */
    EClass READ_ON = eINSTANCE.getREAD_ON();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference READ_ON__ELEMENT = eINSTANCE.getREAD_ON_Element();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.ReadableImpl <em>Readable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.ReadableImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getReadable()
     * @generated
     */
    EClass READABLE = eINSTANCE.getReadable();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference READABLE__PARAMS = eINSTANCE.getReadable_Params();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READABLE__NUMBER = eINSTANCE.getReadable_Number();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.InsertableImpl <em>Insertable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.InsertableImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getInsertable()
     * @generated
     */
    EClass INSERTABLE = eINSTANCE.getInsertable();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.VerifiableImpl <em>Verifiable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.VerifiableImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getVerifiable()
     * @generated
     */
    EClass VERIFIABLE = eINSTANCE.getVerifiable();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.ClickableImpl <em>Clickable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.ClickableImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getClickable()
     * @generated
     */
    EClass CLICKABLE = eINSTANCE.getClickable();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.COMBOBOXImpl <em>COMBOBOX</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.COMBOBOXImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCOMBOBOX()
     * @generated
     */
    EClass COMBOBOX = eINSTANCE.getCOMBOBOX();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__NAME = eINSTANCE.getCOMBOBOX_Name();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.CHECKBOXImpl <em>CHECKBOX</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.CHECKBOXImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getCHECKBOX()
     * @generated
     */
    EClass CHECKBOX = eINSTANCE.getCHECKBOX();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__NAME = eINSTANCE.getCHECKBOX_Name();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.SEARCH_FIELDImpl <em>SEARCH FIELD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.SEARCH_FIELDImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getSEARCH_FIELD()
     * @generated
     */
    EClass SEARCH_FIELD = eINSTANCE.getSEARCH_FIELD();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEARCH_FIELD__NAME = eINSTANCE.getSEARCH_FIELD_Name();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.TEXTImpl <em>TEXT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.TEXTImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getTEXT()
     * @generated
     */
    EClass TEXT = eINSTANCE.getTEXT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__NAME = eINSTANCE.getTEXT_Name();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.BUTTONImpl <em>BUTTON</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BUTTONImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getBUTTON()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getBUTTON();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__NAME = eINSTANCE.getBUTTON_Name();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.LINKImpl <em>LINK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.LINKImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getLINK()
     * @generated
     */
    EClass LINK = eINSTANCE.getLINK();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__URL = eINSTANCE.getLINK_Url();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.IMAGEImpl <em>IMAGE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.IMAGEImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getIMAGE()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getIMAGE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__NAME = eINSTANCE.getIMAGE_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__PARAMS = eINSTANCE.getIMAGE_Params();

    /**
     * The meta object literal for the '{@link org.xtext.imt.browserautomation.browserAutomation.impl.PARAMSImpl <em>PARAMS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.PARAMSImpl
     * @see org.xtext.imt.browserautomation.browserAutomation.impl.BrowserAutomationPackageImpl#getPARAMS()
     * @generated
     */
    EClass PARAMS = eINSTANCE.getPARAMS();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMS__KEY = eINSTANCE.getPARAMS_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMS__VALUE = eINSTANCE.getPARAMS_Value();

  }

} //BrowserAutomationPackage
