/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OPEN BROWSER</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getOPEN_BROWSER()
 * @model
 * @generated
 */
public interface OPEN_BROWSER extends Instruction
{
} // OPEN_BROWSER
