/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Readable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getReadable()
 * @model
 * @generated
 */
public interface Readable extends EObject
{
} // Readable
