/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation;

import org.xtext.imt.browserautomation.BrowserAutomationStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BrowserAutomationStandaloneSetup extends BrowserAutomationStandaloneSetupGenerated {
  public static void doSetup() {
    new BrowserAutomationStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
