/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.ide;

import org.xtext.imt.browserautomation.ide.AbstractBrowserAutomationIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BrowserAutomationIdeModule extends AbstractBrowserAutomationIdeModule {
}
