/*
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.imt.browserautomationselenium.ui.internal.BrowserautomationseleniumActivator;

public class BrowserAutomationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BrowserautomationseleniumActivator.getInstance().getInjector("org.xtext.imt.browserautomation.BrowserAutomation");
	}

}
