/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage;
import org.xtext.imt.browserautomation.browserAutomation.OPEN_BROWSER;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>OPEN BROWSER</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OPEN_BROWSERImpl extends InstructionImpl implements OPEN_BROWSER
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OPEN_BROWSERImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserAutomationPackage.Literals.OPEN_BROWSER;
  }

} //OPEN_BROWSERImpl
