/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Readable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReadableImpl extends MinimalEObjectImpl.Container implements org.xtext.imt.browserautomation.browserAutomation.Readable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReadableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserAutomationPackage.Literals.READABLE;
  }

} //ReadableImpl
