/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LINK</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.browserautomation.browserAutomation.LINK#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getLINK()
 * @model
 * @generated
 */
public interface LINK extends org.xtext.imt.browserautomation.browserAutomation.Readable, Verifiable, Clickable
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getLINK_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link org.xtext.imt.browserautomation.browserAutomation.LINK#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

} // LINK
