/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Suites</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.browserautomation.browserAutomation.TestSuites#getTestsuites <em>Testsuites</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getTestSuites()
 * @model
 * @generated
 */
public interface TestSuites extends EObject
{
  /**
   * Returns the value of the '<em><b>Testsuites</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.imt.browserautomation.browserAutomation.TestSuite}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Testsuites</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Testsuites</em>' containment reference list.
   * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getTestSuites_Testsuites()
   * @model containment="true"
   * @generated
   */
  EList<TestSuite> getTestsuites();

} // TestSuites
