/**
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.browserAutomation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Suite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.browserautomation.browserAutomation.TestSuite#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.imt.browserautomation.browserAutomation.TestSuite#getTests <em>Tests</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getTestSuite()
 * @model
 * @generated
 */
public interface TestSuite extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getTestSuite_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.imt.browserautomation.browserAutomation.TestSuite#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tests</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.imt.browserautomation.browserAutomation.Test}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tests</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tests</em>' containment reference list.
   * @see org.xtext.imt.browserautomation.browserAutomation.BrowserAutomationPackage#getTestSuite_Tests()
   * @model containment="true"
   * @generated
   */
  EList<Test> getTests();

} // TestSuite
