/*
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BrowserAutomationStandaloneSetup extends BrowserAutomationStandaloneSetupGenerated {

	def static void doSetup() {
		new BrowserAutomationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
