/*
 * generated by Xtext 2.15.0
 */
package org.xtext.imt.browserautomation.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BrowserAutomationGrammarAccess extends AbstractGrammarElementFinder {
	
	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTestAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTestKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cResultKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cResultAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cResultBOOLParserRuleCall_5_0 = (RuleCall)cResultAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInstructionsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cInstructionsInstructionParserRuleCall_7_0 = (RuleCall)cInstructionsAssignment_7.eContents().get(0);
		private final Keyword cEndKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Test:
		//	{Test}
		//	'Test' name=STRING '(' 'result=' result=BOOL ')'
		//	instructions+=Instruction*
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//{Test} 'Test' name=STRING '(' 'result=' result=BOOL ')' instructions+=Instruction* 'end'
		public Group getGroup() { return cGroup; }
		
		//{Test}
		public Action getTestAction_0() { return cTestAction_0; }
		
		//'Test'
		public Keyword getTestKeyword_1() { return cTestKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//'result='
		public Keyword getResultKeyword_4() { return cResultKeyword_4; }
		
		//result=BOOL
		public Assignment getResultAssignment_5() { return cResultAssignment_5; }
		
		//BOOL
		public RuleCall getResultBOOLParserRuleCall_5_0() { return cResultBOOLParserRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment_7() { return cInstructionsAssignment_7; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_7_0() { return cInstructionsInstructionParserRuleCall_7_0; }
		
		//'end'
		public Keyword getEndKeyword_8() { return cEndKeyword_8; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAFFECTATIONParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOPEN_BROWSERParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGO_TO_URLParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCLICK_ONParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cVERIFY_THATParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cINSERT_ONParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cCHECK_BOXEParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cCHOOSE_COMBOBOXParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cREAD_ONParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Instruction:
		//	AFFECTATION | OPEN_BROWSER | GO_TO_URL | CLICK_ON | VERIFY_THAT | INSERT_ON | CHECK_BOXE | CHOOSE_COMBOBOX | READ_ON;
		@Override public ParserRule getRule() { return rule; }
		
		//AFFECTATION | OPEN_BROWSER | GO_TO_URL | CLICK_ON | VERIFY_THAT | INSERT_ON | CHECK_BOXE | CHOOSE_COMBOBOX | READ_ON
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AFFECTATION
		public RuleCall getAFFECTATIONParserRuleCall_0() { return cAFFECTATIONParserRuleCall_0; }
		
		//OPEN_BROWSER
		public RuleCall getOPEN_BROWSERParserRuleCall_1() { return cOPEN_BROWSERParserRuleCall_1; }
		
		//GO_TO_URL
		public RuleCall getGO_TO_URLParserRuleCall_2() { return cGO_TO_URLParserRuleCall_2; }
		
		//CLICK_ON
		public RuleCall getCLICK_ONParserRuleCall_3() { return cCLICK_ONParserRuleCall_3; }
		
		//VERIFY_THAT
		public RuleCall getVERIFY_THATParserRuleCall_4() { return cVERIFY_THATParserRuleCall_4; }
		
		//INSERT_ON
		public RuleCall getINSERT_ONParserRuleCall_5() { return cINSERT_ONParserRuleCall_5; }
		
		//CHECK_BOXE
		public RuleCall getCHECK_BOXEParserRuleCall_6() { return cCHECK_BOXEParserRuleCall_6; }
		
		//CHOOSE_COMBOBOX
		public RuleCall getCHOOSE_COMBOBOXParserRuleCall_7() { return cCHOOSE_COMBOBOXParserRuleCall_7; }
		
		//READ_ON
		public RuleCall getREAD_ONParserRuleCall_8() { return cREAD_ONParserRuleCall_8; }
	}
	public class AFFECTATIONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.AFFECTATION");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cElementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSelectorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSelectorSELECTORParserRuleCall_3_0 = (RuleCall)cSelectorAssignment_3.eContents().get(0);
		
		//AFFECTATION:
		//	'element' name=ID '=' selector=SELECTOR;
		@Override public ParserRule getRule() { return rule; }
		
		//'element' name=ID '=' selector=SELECTOR
		public Group getGroup() { return cGroup; }
		
		//'element'
		public Keyword getElementKeyword_0() { return cElementKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//selector=SELECTOR
		public Assignment getSelectorAssignment_3() { return cSelectorAssignment_3; }
		
		//SELECTOR
		public RuleCall getSelectorSELECTORParserRuleCall_3_0() { return cSelectorSELECTORParserRuleCall_3_0; }
	}
	public class SELECTORElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.SELECTOR");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFindKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cReadableParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cParamsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParamsPARAMSParserRuleCall_3_0 = (RuleCall)cParamsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNumberAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNumberINTTerminalRuleCall_6_0 = (RuleCall)cNumberAssignment_6.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//SELECTOR:
		//	'find' Readable '{' params+=PARAMS '}' '[' number=INT ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'find' Readable '{' params+=PARAMS '}' '[' number=INT ']'
		public Group getGroup() { return cGroup; }
		
		//'find'
		public Keyword getFindKeyword_0() { return cFindKeyword_0; }
		
		//Readable
		public RuleCall getReadableParserRuleCall_1() { return cReadableParserRuleCall_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//params+=PARAMS
		public Assignment getParamsAssignment_3() { return cParamsAssignment_3; }
		
		//PARAMS
		public RuleCall getParamsPARAMSParserRuleCall_3_0() { return cParamsPARAMSParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//number=INT
		public Assignment getNumberAssignment_6() { return cNumberAssignment_6; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_6_0() { return cNumberINTTerminalRuleCall_6_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_7() { return cRightSquareBracketKeyword_7; }
	}
	public class RefElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.RefElement");
		private final Assignment cRefAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cRefAFFECTATIONCrossReference_0 = (CrossReference)cRefAssignment.eContents().get(0);
		private final RuleCall cRefAFFECTATIONIDTerminalRuleCall_0_1 = (RuleCall)cRefAFFECTATIONCrossReference_0.eContents().get(1);
		
		//RefElement:
		//	ref=[AFFECTATION];
		@Override public ParserRule getRule() { return rule; }
		
		//ref=[AFFECTATION]
		public Assignment getRefAssignment() { return cRefAssignment; }
		
		//[AFFECTATION]
		public CrossReference getRefAFFECTATIONCrossReference_0() { return cRefAFFECTATIONCrossReference_0; }
		
		//ID
		public RuleCall getRefAFFECTATIONIDTerminalRuleCall_0_1() { return cRefAFFECTATIONIDTerminalRuleCall_0_1; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Element");
		private final Assignment cIdAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_0 = (RuleCall)cIdAssignment.eContents().get(0);
		
		//Element:
		//	Id=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//Id=ID
		public Assignment getIdAssignment() { return cIdAssignment; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_0() { return cIdIDTerminalRuleCall_0; }
	}
	public class BOOLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.BOOL");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTRUEKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFALSEKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//BOOL:
		//	'TRUE' | 'FALSE';
		@Override public ParserRule getRule() { return rule; }
		
		//'TRUE' | 'FALSE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'TRUE'
		public Keyword getTRUEKeyword_0() { return cTRUEKeyword_0; }
		
		//'FALSE'
		public Keyword getFALSEKeyword_1() { return cFALSEKeyword_1; }
	}
	public class OPEN_BROWSERElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.OPEN_BROWSER");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOPEN_BROWSERAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOpenBrowserKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//OPEN_BROWSER:
		//	{OPEN_BROWSER}
		//	'openBrowser';
		@Override public ParserRule getRule() { return rule; }
		
		//{OPEN_BROWSER} 'openBrowser'
		public Group getGroup() { return cGroup; }
		
		//{OPEN_BROWSER}
		public Action getOPEN_BROWSERAction_0() { return cOPEN_BROWSERAction_0; }
		
		//'openBrowser'
		public Keyword getOpenBrowserKeyword_1() { return cOpenBrowserKeyword_1; }
	}
	public class GO_TO_URLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.GO_TO_URL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpenpageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		
		//GO_TO_URL:
		//	'openpage' url=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'openpage' url=STRING
		public Group getGroup() { return cGroup; }
		
		//'openpage'
		public Keyword getOpenpageKeyword_0() { return cOpenpageKeyword_0; }
		
		//url=STRING
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }
		
		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_1_0() { return cUrlSTRINGTerminalRuleCall_1_0; }
	}
	public class CLICK_ONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.CLICK_ON");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClickOnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementClickableParserRuleCall_1_0 = (RuleCall)cElementAssignment_1.eContents().get(0);
		
		//CLICK_ON:
		//	'clickOn' element=Clickable;
		@Override public ParserRule getRule() { return rule; }
		
		//'clickOn' element=Clickable
		public Group getGroup() { return cGroup; }
		
		//'clickOn'
		public Keyword getClickOnKeyword_0() { return cClickOnKeyword_0; }
		
		//element=Clickable
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//Clickable
		public RuleCall getElementClickableParserRuleCall_1_0() { return cElementClickableParserRuleCall_1_0; }
	}
	public class VERIFY_THATElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.VERIFY_THAT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerifyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementVerifiableParserRuleCall_1_0 = (RuleCall)cElementAssignment_1.eContents().get(0);
		
		//VERIFY_THAT:
		//	'verify' element=Verifiable;
		@Override public ParserRule getRule() { return rule; }
		
		//'verify' element=Verifiable
		public Group getGroup() { return cGroup; }
		
		//'verify'
		public Keyword getVerifyKeyword_0() { return cVerifyKeyword_0; }
		
		//element=Verifiable
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//Verifiable
		public RuleCall getElementVerifiableParserRuleCall_1_0() { return cElementVerifiableParserRuleCall_1_0; }
	}
	public class INSERT_ONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.INSERT_ON");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInsertKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementInsertableParserRuleCall_1_0 = (RuleCall)cElementAssignment_1.eContents().get(0);
		private final Assignment cDataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cDataAlternatives_2_0 = (Alternatives)cDataAssignment_2.eContents().get(0);
		private final RuleCall cDataSTRINGTerminalRuleCall_2_0_0 = (RuleCall)cDataAlternatives_2_0.eContents().get(0);
		private final RuleCall cDataIDTerminalRuleCall_2_0_1 = (RuleCall)cDataAlternatives_2_0.eContents().get(1);
		
		//INSERT_ON:
		//	'insert' element=Insertable data=(STRING | ID);
		@Override public ParserRule getRule() { return rule; }
		
		//'insert' element=Insertable data=(STRING | ID)
		public Group getGroup() { return cGroup; }
		
		//'insert'
		public Keyword getInsertKeyword_0() { return cInsertKeyword_0; }
		
		//element=Insertable
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//Insertable
		public RuleCall getElementInsertableParserRuleCall_1_0() { return cElementInsertableParserRuleCall_1_0; }
		
		//data=(STRING | ID)
		public Assignment getDataAssignment_2() { return cDataAssignment_2; }
		
		//(STRING | ID)
		public Alternatives getDataAlternatives_2_0() { return cDataAlternatives_2_0; }
		
		//STRING
		public RuleCall getDataSTRINGTerminalRuleCall_2_0_0() { return cDataSTRINGTerminalRuleCall_2_0_0; }
		
		//ID
		public RuleCall getDataIDTerminalRuleCall_2_0_1() { return cDataIDTerminalRuleCall_2_0_1; }
	}
	public class CHECK_BOXEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.CHECK_BOXE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cUncheckKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cCheckKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cElementAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cElementCHECKBOXParserRuleCall_1_0_0 = (RuleCall)cElementAssignment_1_0.eContents().get(0);
		private final Keyword cALLKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		
		//CHECK_BOXE:
		//	('uncheck' | 'check') (element+=CHECKBOX* | 'ALL');
		@Override public ParserRule getRule() { return rule; }
		
		//('uncheck' | 'check') (element+=CHECKBOX* | 'ALL')
		public Group getGroup() { return cGroup; }
		
		//'uncheck' | 'check'
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'uncheck'
		public Keyword getUncheckKeyword_0_0() { return cUncheckKeyword_0_0; }
		
		//'check'
		public Keyword getCheckKeyword_0_1() { return cCheckKeyword_0_1; }
		
		//element+=CHECKBOX* | 'ALL'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//element+=CHECKBOX*
		public Assignment getElementAssignment_1_0() { return cElementAssignment_1_0; }
		
		//CHECKBOX
		public RuleCall getElementCHECKBOXParserRuleCall_1_0_0() { return cElementCHECKBOXParserRuleCall_1_0_0; }
		
		//'ALL'
		public Keyword getALLKeyword_1_1() { return cALLKeyword_1_1; }
	}
	public class CHOOSE_COMBOBOXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.CHOOSE_COMBOBOX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoosecomboKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementCOMBOBOXParserRuleCall_1_0 = (RuleCall)cElementAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDataAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDataSTRINGTerminalRuleCall_3_0 = (RuleCall)cDataAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//CHOOSE_COMBOBOX:
		//	'choosecombo' element=COMBOBOX '{' data=STRING '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'choosecombo' element=COMBOBOX '{' data=STRING '}'
		public Group getGroup() { return cGroup; }
		
		//'choosecombo'
		public Keyword getChoosecomboKeyword_0() { return cChoosecomboKeyword_0; }
		
		//element=COMBOBOX
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//COMBOBOX
		public RuleCall getElementCOMBOBOXParserRuleCall_1_0() { return cElementCOMBOBOXParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//data=STRING
		public Assignment getDataAssignment_3() { return cDataAssignment_3; }
		
		//STRING
		public RuleCall getDataSTRINGTerminalRuleCall_3_0() { return cDataSTRINGTerminalRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class READ_ONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.READ_ON");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementReadableParserRuleCall_1_0 = (RuleCall)cElementAssignment_1.eContents().get(0);
		
		//READ_ON:
		//	'read' element=Readable;
		@Override public ParserRule getRule() { return rule; }
		
		//'read' element=Readable
		public Group getGroup() { return cGroup; }
		
		//'read'
		public Keyword getReadKeyword_0() { return cReadKeyword_0; }
		
		//element=Readable
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//Readable
		public RuleCall getElementReadableParserRuleCall_1_0() { return cElementReadableParserRuleCall_1_0; }
	}
	public class ReadableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Readable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTEXTParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBUTTONParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLINKParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Readable:
		//	TEXT | BUTTON | LINK;
		@Override public ParserRule getRule() { return rule; }
		
		//TEXT | BUTTON | LINK
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TEXT
		public RuleCall getTEXTParserRuleCall_0() { return cTEXTParserRuleCall_0; }
		
		//BUTTON
		public RuleCall getBUTTONParserRuleCall_1() { return cBUTTONParserRuleCall_1; }
		
		//LINK
		public RuleCall getLINKParserRuleCall_2() { return cLINKParserRuleCall_2; }
	}
	public class InsertableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Insertable");
		private final RuleCall cSEARCH_FIELDParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Insertable:
		//	SEARCH_FIELD;
		@Override public ParserRule getRule() { return rule; }
		
		//SEARCH_FIELD
		public RuleCall getSEARCH_FIELDParserRuleCall() { return cSEARCH_FIELDParserRuleCall; }
	}
	public class VerifiableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Verifiable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTEXTParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBUTTONParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLINKParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cIMAGEParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRefElementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Verifiable:
		//	TEXT | BUTTON | LINK | IMAGE | RefElement;
		@Override public ParserRule getRule() { return rule; }
		
		//TEXT | BUTTON | LINK | IMAGE | RefElement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TEXT
		public RuleCall getTEXTParserRuleCall_0() { return cTEXTParserRuleCall_0; }
		
		//BUTTON
		public RuleCall getBUTTONParserRuleCall_1() { return cBUTTONParserRuleCall_1; }
		
		//LINK
		public RuleCall getLINKParserRuleCall_2() { return cLINKParserRuleCall_2; }
		
		//IMAGE
		public RuleCall getIMAGEParserRuleCall_3() { return cIMAGEParserRuleCall_3; }
		
		//RefElement
		public RuleCall getRefElementParserRuleCall_4() { return cRefElementParserRuleCall_4; }
	}
	public class ClickableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.Clickable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBUTTONParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLINKParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIMAGEParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCOMBOBOXParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRefElementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Clickable:
		//	BUTTON | LINK | IMAGE | COMBOBOX | RefElement;
		@Override public ParserRule getRule() { return rule; }
		
		//BUTTON | LINK | IMAGE | COMBOBOX | RefElement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BUTTON
		public RuleCall getBUTTONParserRuleCall_0() { return cBUTTONParserRuleCall_0; }
		
		//LINK
		public RuleCall getLINKParserRuleCall_1() { return cLINKParserRuleCall_1; }
		
		//IMAGE
		public RuleCall getIMAGEParserRuleCall_2() { return cIMAGEParserRuleCall_2; }
		
		//COMBOBOX
		public RuleCall getCOMBOBOXParserRuleCall_3() { return cCOMBOBOXParserRuleCall_3; }
		
		//RefElement
		public RuleCall getRefElementParserRuleCall_4() { return cRefElementParserRuleCall_4; }
	}
	public class COMBOBOXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.COMBOBOX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComboboxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//COMBOBOX:
		//	'combobox' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'combobox' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'combobox'
		public Keyword getComboboxKeyword_0() { return cComboboxKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class CHECKBOXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.CHECKBOX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheckboxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//CHECKBOX:
		//	'checkbox' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'checkbox' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'checkbox'
		public Keyword getCheckboxKeyword_0() { return cCheckboxKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class SEARCH_FIELDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.SEARCH_FIELD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSearchfieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//SEARCH_FIELD:
		//	'searchfield' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'searchfield' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'searchfield'
		public Keyword getSearchfieldKeyword_0() { return cSearchfieldKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class TEXTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.TEXT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//TEXT:
		//	'text' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'text' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'text'
		public Keyword getTextKeyword_0() { return cTextKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class BUTTONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.BUTTON");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cButtonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//BUTTON:
		//	'button' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'button' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'button'
		public Keyword getButtonKeyword_0() { return cButtonKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class LINKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.LINK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLinkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		
		//LINK:
		//	'link' url=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'link' url=STRING
		public Group getGroup() { return cGroup; }
		
		//'link'
		public Keyword getLinkKeyword_0() { return cLinkKeyword_0; }
		
		//url=STRING
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }
		
		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_1_0() { return cUrlSTRINGTerminalRuleCall_1_0; }
	}
	public class IMAGEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.IMAGE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParamsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cParamsPARAMSParserRuleCall_2_1_0 = (RuleCall)cParamsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//IMAGE:
		//	'image' name=STRING ('{' params+=PARAMS* '}')*;
		@Override public ParserRule getRule() { return rule; }
		
		//'image' name=STRING ('{' params+=PARAMS* '}')*
		public Group getGroup() { return cGroup; }
		
		//'image'
		public Keyword getImageKeyword_0() { return cImageKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//('{' params+=PARAMS* '}')*
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//params+=PARAMS*
		public Assignment getParamsAssignment_2_1() { return cParamsAssignment_2_1; }
		
		//PARAMS
		public RuleCall getParamsPARAMSParserRuleCall_2_1_0() { return cParamsPARAMSParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_2() { return cRightCurlyBracketKeyword_2_2; }
	}
	public class PARAMSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.imt.browserautomation.BrowserAutomation.PARAMS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeySTRINGTerminalRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//PARAMS:
		//	key=STRING '=' value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//key=STRING '=' value=STRING
		public Group getGroup() { return cGroup; }
		
		//key=STRING
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }
		
		//STRING
		public RuleCall getKeySTRINGTerminalRuleCall_0_0() { return cKeySTRINGTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//value=STRING
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0() { return cValueSTRINGTerminalRuleCall_2_0; }
	}
	
	
	private final TestElements pTest;
	private final InstructionElements pInstruction;
	private final AFFECTATIONElements pAFFECTATION;
	private final SELECTORElements pSELECTOR;
	private final RefElementElements pRefElement;
	private final ElementElements pElement;
	private final BOOLElements pBOOL;
	private final OPEN_BROWSERElements pOPEN_BROWSER;
	private final GO_TO_URLElements pGO_TO_URL;
	private final CLICK_ONElements pCLICK_ON;
	private final VERIFY_THATElements pVERIFY_THAT;
	private final INSERT_ONElements pINSERT_ON;
	private final CHECK_BOXEElements pCHECK_BOXE;
	private final CHOOSE_COMBOBOXElements pCHOOSE_COMBOBOX;
	private final READ_ONElements pREAD_ON;
	private final ReadableElements pReadable;
	private final InsertableElements pInsertable;
	private final VerifiableElements pVerifiable;
	private final ClickableElements pClickable;
	private final COMBOBOXElements pCOMBOBOX;
	private final CHECKBOXElements pCHECKBOX;
	private final SEARCH_FIELDElements pSEARCH_FIELD;
	private final TEXTElements pTEXT;
	private final BUTTONElements pBUTTON;
	private final LINKElements pLINK;
	private final IMAGEElements pIMAGE;
	private final PARAMSElements pPARAMS;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BrowserAutomationGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTest = new TestElements();
		this.pInstruction = new InstructionElements();
		this.pAFFECTATION = new AFFECTATIONElements();
		this.pSELECTOR = new SELECTORElements();
		this.pRefElement = new RefElementElements();
		this.pElement = new ElementElements();
		this.pBOOL = new BOOLElements();
		this.pOPEN_BROWSER = new OPEN_BROWSERElements();
		this.pGO_TO_URL = new GO_TO_URLElements();
		this.pCLICK_ON = new CLICK_ONElements();
		this.pVERIFY_THAT = new VERIFY_THATElements();
		this.pINSERT_ON = new INSERT_ONElements();
		this.pCHECK_BOXE = new CHECK_BOXEElements();
		this.pCHOOSE_COMBOBOX = new CHOOSE_COMBOBOXElements();
		this.pREAD_ON = new READ_ONElements();
		this.pReadable = new ReadableElements();
		this.pInsertable = new InsertableElements();
		this.pVerifiable = new VerifiableElements();
		this.pClickable = new ClickableElements();
		this.pCOMBOBOX = new COMBOBOXElements();
		this.pCHECKBOX = new CHECKBOXElements();
		this.pSEARCH_FIELD = new SEARCH_FIELDElements();
		this.pTEXT = new TEXTElements();
		this.pBUTTON = new BUTTONElements();
		this.pLINK = new LINKElements();
		this.pIMAGE = new IMAGEElements();
		this.pPARAMS = new PARAMSElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.imt.browserautomation.BrowserAutomation".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Test:
	//	{Test}
	//	'Test' name=STRING '(' 'result=' result=BOOL ')'
	//	instructions+=Instruction*
	//	'end';
	public TestElements getTestAccess() {
		return pTest;
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}
	
	//Instruction:
	//	AFFECTATION | OPEN_BROWSER | GO_TO_URL | CLICK_ON | VERIFY_THAT | INSERT_ON | CHECK_BOXE | CHOOSE_COMBOBOX | READ_ON;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//AFFECTATION:
	//	'element' name=ID '=' selector=SELECTOR;
	public AFFECTATIONElements getAFFECTATIONAccess() {
		return pAFFECTATION;
	}
	
	public ParserRule getAFFECTATIONRule() {
		return getAFFECTATIONAccess().getRule();
	}
	
	//SELECTOR:
	//	'find' Readable '{' params+=PARAMS '}' '[' number=INT ']';
	public SELECTORElements getSELECTORAccess() {
		return pSELECTOR;
	}
	
	public ParserRule getSELECTORRule() {
		return getSELECTORAccess().getRule();
	}
	
	//RefElement:
	//	ref=[AFFECTATION];
	public RefElementElements getRefElementAccess() {
		return pRefElement;
	}
	
	public ParserRule getRefElementRule() {
		return getRefElementAccess().getRule();
	}
	
	//Element:
	//	Id=ID;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//BOOL:
	//	'TRUE' | 'FALSE';
	public BOOLElements getBOOLAccess() {
		return pBOOL;
	}
	
	public ParserRule getBOOLRule() {
		return getBOOLAccess().getRule();
	}
	
	//OPEN_BROWSER:
	//	{OPEN_BROWSER}
	//	'openBrowser';
	public OPEN_BROWSERElements getOPEN_BROWSERAccess() {
		return pOPEN_BROWSER;
	}
	
	public ParserRule getOPEN_BROWSERRule() {
		return getOPEN_BROWSERAccess().getRule();
	}
	
	//GO_TO_URL:
	//	'openpage' url=STRING;
	public GO_TO_URLElements getGO_TO_URLAccess() {
		return pGO_TO_URL;
	}
	
	public ParserRule getGO_TO_URLRule() {
		return getGO_TO_URLAccess().getRule();
	}
	
	//CLICK_ON:
	//	'clickOn' element=Clickable;
	public CLICK_ONElements getCLICK_ONAccess() {
		return pCLICK_ON;
	}
	
	public ParserRule getCLICK_ONRule() {
		return getCLICK_ONAccess().getRule();
	}
	
	//VERIFY_THAT:
	//	'verify' element=Verifiable;
	public VERIFY_THATElements getVERIFY_THATAccess() {
		return pVERIFY_THAT;
	}
	
	public ParserRule getVERIFY_THATRule() {
		return getVERIFY_THATAccess().getRule();
	}
	
	//INSERT_ON:
	//	'insert' element=Insertable data=(STRING | ID);
	public INSERT_ONElements getINSERT_ONAccess() {
		return pINSERT_ON;
	}
	
	public ParserRule getINSERT_ONRule() {
		return getINSERT_ONAccess().getRule();
	}
	
	//CHECK_BOXE:
	//	('uncheck' | 'check') (element+=CHECKBOX* | 'ALL');
	public CHECK_BOXEElements getCHECK_BOXEAccess() {
		return pCHECK_BOXE;
	}
	
	public ParserRule getCHECK_BOXERule() {
		return getCHECK_BOXEAccess().getRule();
	}
	
	//CHOOSE_COMBOBOX:
	//	'choosecombo' element=COMBOBOX '{' data=STRING '}';
	public CHOOSE_COMBOBOXElements getCHOOSE_COMBOBOXAccess() {
		return pCHOOSE_COMBOBOX;
	}
	
	public ParserRule getCHOOSE_COMBOBOXRule() {
		return getCHOOSE_COMBOBOXAccess().getRule();
	}
	
	//READ_ON:
	//	'read' element=Readable;
	public READ_ONElements getREAD_ONAccess() {
		return pREAD_ON;
	}
	
	public ParserRule getREAD_ONRule() {
		return getREAD_ONAccess().getRule();
	}
	
	//Readable:
	//	TEXT | BUTTON | LINK;
	public ReadableElements getReadableAccess() {
		return pReadable;
	}
	
	public ParserRule getReadableRule() {
		return getReadableAccess().getRule();
	}
	
	//Insertable:
	//	SEARCH_FIELD;
	public InsertableElements getInsertableAccess() {
		return pInsertable;
	}
	
	public ParserRule getInsertableRule() {
		return getInsertableAccess().getRule();
	}
	
	//Verifiable:
	//	TEXT | BUTTON | LINK | IMAGE | RefElement;
	public VerifiableElements getVerifiableAccess() {
		return pVerifiable;
	}
	
	public ParserRule getVerifiableRule() {
		return getVerifiableAccess().getRule();
	}
	
	//Clickable:
	//	BUTTON | LINK | IMAGE | COMBOBOX | RefElement;
	public ClickableElements getClickableAccess() {
		return pClickable;
	}
	
	public ParserRule getClickableRule() {
		return getClickableAccess().getRule();
	}
	
	//COMBOBOX:
	//	'combobox' name=STRING;
	public COMBOBOXElements getCOMBOBOXAccess() {
		return pCOMBOBOX;
	}
	
	public ParserRule getCOMBOBOXRule() {
		return getCOMBOBOXAccess().getRule();
	}
	
	//CHECKBOX:
	//	'checkbox' name=STRING;
	public CHECKBOXElements getCHECKBOXAccess() {
		return pCHECKBOX;
	}
	
	public ParserRule getCHECKBOXRule() {
		return getCHECKBOXAccess().getRule();
	}
	
	//SEARCH_FIELD:
	//	'searchfield' name=STRING;
	public SEARCH_FIELDElements getSEARCH_FIELDAccess() {
		return pSEARCH_FIELD;
	}
	
	public ParserRule getSEARCH_FIELDRule() {
		return getSEARCH_FIELDAccess().getRule();
	}
	
	//TEXT:
	//	'text' name=STRING;
	public TEXTElements getTEXTAccess() {
		return pTEXT;
	}
	
	public ParserRule getTEXTRule() {
		return getTEXTAccess().getRule();
	}
	
	//BUTTON:
	//	'button' name=STRING;
	public BUTTONElements getBUTTONAccess() {
		return pBUTTON;
	}
	
	public ParserRule getBUTTONRule() {
		return getBUTTONAccess().getRule();
	}
	
	//LINK:
	//	'link' url=STRING;
	public LINKElements getLINKAccess() {
		return pLINK;
	}
	
	public ParserRule getLINKRule() {
		return getLINKAccess().getRule();
	}
	
	//IMAGE:
	//	'image' name=STRING ('{' params+=PARAMS* '}')*;
	public IMAGEElements getIMAGEAccess() {
		return pIMAGE;
	}
	
	public ParserRule getIMAGERule() {
		return getIMAGEAccess().getRule();
	}
	
	//PARAMS:
	//	key=STRING '=' value=STRING;
	public PARAMSElements getPARAMSAccess() {
		return pPARAMS;
	}
	
	public ParserRule getPARAMSRule() {
		return getPARAMSAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
